Repository AniAPI-Team/AniAPI, pull requests merged in 2021-08, with the labels that each got.

#19 Update "Help us" link on README
  README.md
Labels: documentation

#20 1.0.x
  Commons/User.cs
  SyncService/Models/AnimeMatching.cs
  SyncService/Models/IWebsiteScraper.cs
  SyncService/Models/WebsiteScrapers/AnimeworldScraper.cs
  SyncService/Models/WebsiteScrapers/DreamsubScraper.cs
  SyncService/Models/WebsiteScrapers/GogoanimeScraper.cs
  WebAPI/Controllers/UserController.cs
Labels: enhancement

#21 1.0.x
  .github/FUNDING.yml
  SyncService/Models/WebsiteScrapers/GogoanimeScraper.cs
  WebAPI/Controllers/ProxyController.cs
  WebAPI/WebAPI.xml
Labels: enhancement, done

#22 Update packages + fix Null Ref.
  Commons/Commons.csproj
  ServiceMongo/ServiceMongo.csproj
  SyncService/Models/WebsiteScrapers/AnimeworldScraper.cs
  SyncService/Models/WebsiteScrapers/DreamsubScraper.cs
  SyncService/SyncService.csproj
  WebAPI/WebAPI.csproj
Labels: bug, done

#23 README update
  README.md
Labels: documentation, done
